$:.push File.expand_path("../../lib", __FILE__)

if defined?(VagrantPlugins::VagrantBosh)
  raise "vagrant-bosh plugin is installed via Vagrant. Exiting because lib version will not be used!"
end

require "../lib/vagrant-bosh"

Vagrant.configure("2") do |config|
  # Make sure box has large root partition
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # Example port forward for example-bosh-manifest.yml
  config.vm.network "forwarded_port", guest: 25555, host: 25555 # BOSH Director API

  # Example port forward for example-winston-manifest.yml
  # config.vm.network "forwarded_port", guest: 8080, host: 8080 # http
  # config.vm.network "forwarded_port", guest: 8081, host: 8081 # ws
  # config.vm.network "forwarded_port", guest: 5637, host: 5637 # redgreen

  # Example of custom private network configuration
  # config.vm.network :private_network, ip: "192.168.56.4"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end

  config.vm.provision "bosh" do |c|
    c.manifest = `cat example-bosh-manifest.yml`
    # c.manifest = `cat example-winston-manifest.yml`
  end
end
